version: "2"
services:
  mysql:
    # network_mode: myNetwork
    container_name: pang_mysql
    restart: always
    image: mysql:latest #! คล้ายกับ lib แต่มันคือ image ที่ต้องการให้ทำงานอยู่กับระบบที่กำลังทำงานอยู่
    environment:
      MYSQL_ROOT_PASSWORD: ""
      # MYSQL_USER: 'root'
      # MYSQL_PASS: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
