name: GitHub Actions Demo #! ชื่อ โครงการ
on: [push]
jobs:
  Explore-GitHub-Actions: #! ชื่อ job
    runs-on: ubuntu-latest #! os ที่ใช้งาน
    steps:
      - run: echo "🎉 Hello Pang" #! รันคำสั่ง ubuntu ให้ echo ออกมา
      - uses: snow-actions/line-notify@v1.0.0
       with:
        access_token: sbgUpn2UGSCWs81res3LO3urNXdrCATNmndhuxjboat
        message: Pang ส่งงานแล้ว
